********************************************************************************
* Occupation: 2018 classification
********************************************************************************
/* 2020m1-present: 2018 census occupation codes */
gen occ18 = .

if $monthlycps == 1 {
	if tm(2020m1) <= $date {
		replace occ18 = occcode
	}
}

#delimit ;
lab def occ18
0000 "N/A (Not Applicable)"
0010 "Chief Executives"
0020 "General and Operations Managers"
0030 "Legislators"
0040 "Advertising and Promotions Managers"
0051 "Marketing Managers"
0052 "Sales Managers"
0060 "Public Relations and Fundraising Managers"
0101 "Administrative Services Managers"
0102 "Facilities Managers"
0110 "Computer and Information Systems Managers"
0120 "Financial Managers"
0135 "Compensation and Benefits Managers"
0136 "Human Resources Managers"
0137 "Training and Development Managers"
0140 "Industrial Production Managers"
0150 "Purchasing Managers"
0160 "Transportation, Storage, and Distribution Managers"
0205 "Farmers, Ranchers, and Other Agricultural Managers"
0220 "Construction Managers"
0230 "Education and Childcare Administrators "
0300 "Architectural and Engineering Managers"
0310 "Food Service Managers"
0325 "Funeral Home Managers"
0335 "Entertainment and Recreation Managers"
0340 "Lodging Managers"
0350 "Medical and Health Services Managers"
0360 "Natural Sciences Managers"
0400 "Postmasters and Mail Superintendents"
0410 "Property, Real Estate, and Community Association Managers"
0420 "Social and Community Service Managers"
0425 "Emergency Management Directors"
0426 "Personal Service Managers, All Other"
0440 "Managers, All Other"
0500 "Agents and Business Managers of Artists, Performers, and Athletes"
0510 "Buyers and Purchasing Agents, Farm Products"
0520 "Wholesale and Retail Buyers, Except Farm Products"
0530 "Purchasing Agents, Except Wholesale, Retail, and Farm Products"
0540 "Claims Adjusters, Appraisers, Examiners, and Investigators"
0565 "Compliance Officers"
0600 "Cost Estimators"
0630 "Human Resources Workers"
0640 "Compensation, Benefits, and Job Analysis Specialists"
0650 "Training and Development Specialists"
0700 "Logisticians"
0705 "Project Management Specialists"
0710 "Management Analysts"
0725 "Meeting, Convention, and Event Planners"
0726 "Fundraisers"
0735 "Market Research Analysts and Marketing Specialists"
0750 "Business Operations Specialists, All Other"
0800 "Accountants and Auditors"
0810 "Property Appraisers and Assessors"
0820 "Budget Analysts"
0830 "Credit Analysts"
0845 "Financial and Investment Analysts"
0850 "Personal Financial Advisors"
0860 "Insurance Underwriters"
0900 "Financial Examiners"
0910 "Credit Counselors and Loan Officers"
0930 "Tax Examiners and Collectors, and Revenue Agents"
0940 "Tax Preparers"
0960 "Other Financial Specialists"
1005 "Computer and Information Research Scientists"
1006 "Computer Systems Analysts"
1007 "Information Security Analysts"
1010 "Computer Programmers"
1021 "Software Developers"
1022 "Software Quality Assurance Analysts and Testers"
1031 "Web Developers"
1032 "Web and Digital Interface Designers"
1050 "Computer Support Specialists"
1065 "Database Administrators and Architects"
1105 "Network and Computer Systems Administrators"
1106 "Computer Network Architects"
1108 "Computer Occupations, All Other"
1200 "Actuaries"
1210 "Mathematicians"
1220 "Operations Research Analysts"
1230 "Statisticians"
1240 "Other Mathematical Science Occupations"
1305 "Architects, Except Landscape and Naval"
1306 "Landscape Architects"
1310 "Surveyors, Cartographers, and Photogrammetrists"
1320 "Aerospace Engineers"
1330 "Agricultural Engineers"
1340 "Bioengineers and Biomedical Engineers"
1350 "Chemical Engineers"
1360 "Civil Engineers"
1400 "Computer Hardware Engineers"
1410 "Electrical and Electronics Engineers"
1420 "Environmental Engineers"
1430 "Industrial Engineers, Including Health and Safety "
1440 "Marine Engineers and Naval Architects"
1450 "Materials Engineers"
1460 "Mechanical Engineers"
1500 "Mining and Geological Engineers, Including Mining Safety Engineers"
1510 "Nuclear Engineers"
1520 "Petroleum Engineers"
1530 "Engineers, All Other"
1541 "Architectural and Civil Drafters"
1545 "Other Drafters"
1551 "Electrical and Electronic Engineering Technologists and Technicians"
1555 "Other Engineering Technologists and Technicians, Except Drafters"
1560 "Surveying and Mapping Technicians"
1600 "Agricultural and Food Scientists"
1610 "Biological Scientists"
1640 "Conservation Scientists and Foresters"
1650 "Medical Scientists"
1660 "Life Scientists, All Other"
1700 "Astronomers and Physicists"
1710 "Atmospheric and Space Scientists"
1720 "Chemists and Materials Scientists"
1745 "Environmental Scientists and Specialists, Including Health"
1750 "Geoscientists and Hydrologists, Except Geographers"
1760 "Physical Scientists, All Other"
1800 "Economists"
1815 "Survey Researchers"
1821 "Clinical and Counseling Psychologists"
1822 "School Psychologists"
1825 "Other Psychologists"
1830 "Sociologists"
1840 "Urban and Regional Planners"
1860 "Miscellaneous Social Scientists and Related Workers"
1900 "Agricultural and Food Science Technicians"
1910 "Biological Technicians"
1920 "Chemical Technicians"
1935 "Environmental  Science and Geoscience Technicians"
1940 "Nuclear Technicians"
1950 "Social Science Research Assistants"
1970 "Other Life, Physical, and Social Science Technicians"
1980 "Occupational Health and Safety Specialists and Technicians"
2001 "Substance Abuse and Behavioral Disorder Counselors"
2002 "Educational, Guidance, and Career Counselors and Advisors"
2003 "Marriage and Family Therapists"
2004 "Mental Health Counselors"
2005 "Rehabilitation Counselors"
2006 "Counselors, All Other"
2011 "Child, Family, and School Social Workers"
2012 "Healthcare Social Workers"
2013 "Mental Health and Substance Abuse Social Workers"
2014 "Social Workers, All Other"
2015 "Probation Officers and Correctional Treatment Specialists"
2016 "Social and Human Service Assistants"
2025 "Other Community and Social Service Specialists"
2040 "Clergy"
2050 "Directors, Religious Activities and Education"
2060 "Religious Workers, All Other"
2100 "Lawyers"
2105 "Judicial Law Clerks"
2110 "Judges, Magistrates, and Other Judicial Workers"
2145 "Paralegals and Legal Assistants"
2170 "Title Examiners, Abstractors, and Searchers"
2180 "Legal Support Workers, All Other"
2205 "Postsecondary Teachers"
2300 "Preschool and Kindergarten Teachers"
2310 "Elementary and Middle School Teachers"
2320 "Secondary School Teachers"
2330 "Special Education Teachers"
2350 "Tutors"
2360 "Other Teachers and Instructors"
2400 "Archivists, Curators, and Museum Technicians"
2435 "Librarians and Media Collections Specialists"
2440 "Library Technicians"
2545 "Teaching Assistants"
2555 "Other Educational Instruction and Library Workers"
2600 "Artists and Related Workers"
2631 "Commercial and Industrial Designers"
2632 "Fashion Designers"
2633 "Floral Designers"
2634 "Graphic Designers"
2635 "Interior Designers"
2636 "Merchandise Displayers and Window Trimmers"
2640 "Other Designers"
2700 "Actors"
2710 "Producers and Directors"
2721 "Athletes and Sports Competitors"
2722 "Coaches and Scouts"
2723 "Umpires, Referees, and Other Sports Officials"
2740 "Dancers and Choreographers"
2751 "Music Directors and Composers"
2752 "Musicians and Singers"
2755 "Disc Jockeys, Except Radio "
2770 "Entertainers and Performers, Sports and Related Workers, All Other"
2805 "Broadcast Announcers and Radio Disc Jockeys"
2810 "News Analysts, Reporters, and Journalists"
2825 "Public Relations Specialists"
2830 "Editors"
2840 "Technical Writers"
2850 "Writers and Authors"
2861 "Interpreters and Translators"
2862 "Court Reporters and Simultaneous Captioners"
2865 "Media and Communication Workers, All Other"
2905 "Broadcast, Sound, and Lighting Technicians"
2910 "Photographers"
2920 "Television, Video, and Film Camera Operators and Editors"
2970 "Media and Communication Equipment Workers, All Other"
3000 "Chiropractors"
3010 "Dentists"
3030 "Dietitians and Nutritionists"
3040 "Optometrists"
3050 "Pharmacists"
3065 "Emergency Medicine Physicians"
3070 "Radiologists"
3090 "Other Physicians"
3100 "Surgeons"
3110 "Physician Assistants"
3120 "Podiatrists"
3140 "Audiologists"
3150 "Occupational Therapists"
3160 "Physical Therapists"
3200 "Radiation Therapists"
3210 "Recreational Therapists"
3220 "Respiratory Therapists"
3230 "Speech-Language Pathologists"
3235 "Exercise Physiologists"
3245 "Therapists, All Other"
3250 "Veterinarians"
3255 "Registered Nurses"
3256 "Nurse Anesthetists"
3257 "Nurse Midwives"
3258 "Nurse Practitioners"
3261 "Acupuncturists"
3270 "Healthcare Diagnosing or Treating Practitioners, All Other"
3300 "Clinical Laboratory Technologists and Technicians"
3310 "Dental Hygienists"
3321 "Cardiovascular Technologists and Technicians"
3322 "Diagnostic Medical Sonographers"
3323 "Radiologic Technologists and Technicians"
3324 "Magnetic Resonance Imaging Technologists"
3330 "Nuclear Medicine Technologists and Medical Dosimetrists"
3401 "Emergency Medical Technicians"
3402 "Paramedics"
3421 "Pharmacy Technicians"
3422 "Psychiatric Technicians"
3423 "Surgical Technologists"
3424 "Veterinary Technologists and Technicians"
3430 "Dietetic Technicians and Ophthalmic Medical Technicians"
3500 "Licensed Practical and Licensed Vocational Nurses"
3515 "Medical Records Specialists"
3520 "Opticians, Dispensing"
3545 "Miscellaneous Health Technologists and Technicians"
3550 "Other Healthcare Practitioners and Technical Occupations"
3601 "Home Health Aides"
3602 "Personal Care Aides"
3603 "Nursing Assistants"
3605 "Orderlies and Psychiatric Aides"
3610 "Occupational Therapy Assistants and Aides"
3620 "Physical Therapist Assistants and Aides"
3630 "Massage Therapists"
3640 "Dental Assistants"
3645 "Medical Assistants"
3646 "Medical Transcriptionists"
3647 "Pharmacy Aides"
3648 "Veterinary Assistants and Laboratory Animal Caretakers"
3649 "Phlebotomists"
3655 "Other Healthcare Support Workers"
3700 "First-Line Supervisors of Correctional Officers"
3710 "First-Line Supervisors of Police and Detectives"
3720 "First-Line Supervisors of Firefighting and Prevention Workers"
3725 "First-Line Supervisors of Security Workers"
3735 "First-Line Supervisors of Protective Service Workers, All Other"
3740 "Firefighters"
3750 "Fire Inspectors "
3801 "Bailiffs"
3802 "Correctional Officers and Jailers"
3820 "Detectives and Criminal Investigators"
3830 "Fish and Game Wardens"
3840 "Parking Enforcement Workers"
3870 "Police Officers"
3900 "Animal Control Workers"
3910 "Private Detectives and Investigators"
3930 "Security Guards and Gambling Surveillance Officers"
3940 "Crossing Guards and Flaggers"
3945 "Transportation Security Screeners"
3946 "School Bus Monitors"
3960 "Other Protective Service Workers"
4000 "Chefs and Head Cooks"
4010 "First-Line Supervisors of Food Preparation and Serving Workers"
4020 "Cooks"
4030 "Food Preparation Workers"
4040 "Bartenders"
4055 "Fast Food and Counter Workers"
4110 "Waiters and Waitresses"
4120 "Food Servers, Nonrestaurant"
4130 "Dining Room and Cafeteria Attendants and Bartender Helpers"
4140 "Dishwashers"
4150 "Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop"
4160 "Food Preparation and Serving Related Workers, All Other"
4200 "First-Line Supervisors of Housekeeping and Janitorial Workers"
4210 "First-Line Supervisors of Landscaping, Lawn Service, and Groundskeeping Workers"
4220 "Janitors and Building Cleaners"
4230 "Maids and Housekeeping Cleaners"
4240 "Pest Control Workers"
4251 "Landscaping and Groundskeeping Workers"
4252 "Tree Trimmers and Pruners"
4255 "Other Grounds Maintenance Workers"
4330 "Supervisors of Personal Care and Service Workers"
4340 "Animal Trainers"
4350 "Animal Caretakers"
4400 "Gambling Services Workers"
4420 "Ushers, Lobby Attendants, and Ticket Takers"
4435 "Other Entertainment Attendants and Related Workers"
4461 "Embalmers, Crematory Operators and Funeral Attendants"
4465 "Morticians, Undertakers, and Funeral Arrangers"
4500 "Barbers"
4510 "Hairdressers, Hairstylists, and Cosmetologists"
4521 "Manicurists and Pedicurists"
4522 "Skincare Specialists"
4525 "Other Personal Appearance Workers"
4530 "Baggage Porters, Bellhops, and Concierges"
4540 "Tour and Travel Guides"
4600 "Childcare Workers"
4621 "Exercise Trainers and Group Fitness Instructors"
4622 "Recreation Workers"
4640 "Residential Advisors"
4655 "Personal Care and Service Workers, All Other"
4700 "First-Line Supervisors of Retail Sales Workers"
4710 "First-Line Supervisors of Non-Retail Sales Workers"
4720 "Cashiers"
4740 "Counter and Rental Clerks"
4750 "Parts Salespersons"
4760 "Retail Salespersons"
4800 "Advertising Sales Agents"
4810 "Insurance Sales Agents"
4820 "Securities, Commodities, and Financial Services Sales Agents"
4830 "Travel Agents"
4840 "Sales Representatives of Services, Except Advertising, Insurance, Financial Services, and Travel"
4850 "Sales Representatives, Wholesale and Manufacturing"
4900 "Models, Demonstrators, and Product Promoters"
4920 "Real Estate Brokers and Sales Agents"
4930 "Sales Engineers"
4940 "Telemarketers"
4950 "Door-To-Door Sales Workers, News and Street Vendors, and Related Workers"
4965 "Sales and Related Workers, All Other"
5000 "First-Line Supervisors of Office and Administrative Support Workers"
5010 "Switchboard Operators, Including Answering Service"
5020 "Telephone Operators"
5040 "Communications Equipment Operators, All Other"
5100 "Bill and Account Collectors"
5110 "Billing and Posting Clerks"
5120 "Bookkeeping, Accounting, and Auditing Clerks"
5130 "Gambling Cage Workers"
5140 "Payroll and Timekeeping Clerks"
5150 "Procurement Clerks"
5160 "Tellers"
5165 "Financial Clerks, All Other"
5200 "Brokerage Clerks"
5210 "Correspondence Clerks"
5220 "Court, Municipal, and License Clerks"
5230 "Credit Authorizers, Checkers, and Clerks"
5240 "Customer Service Representatives"
5250 "Eligibility Interviewers, Government Programs"
5260 "File Clerks"
5300 "Hotel, Motel, and Resort Desk Clerks"
5310 "Interviewers, Except Eligibility and Loan"
5320 "Library Assistants, Clerical"
5330 "Loan Interviewers and Clerks"
5340 "New Accounts Clerks"
5350 "Order Clerks"
5360 "Human Resources Assistants, Except Payroll and Timekeeping"
5400 "Receptionists and Information Clerks"
5410 "Reservation and Transportation Ticket Agents and Travel Clerks"
5420 "Information and Record Clerks, All Other"
5500 "Cargo and Freight Agents"
5510 "Couriers and Messengers"
5521 "Public Safety Telecommunicators"
5522 "Dispatchers, Except Police, Fire, and Ambulance"
5530 "Meter Readers, Utilities"
5540 "Postal Service Clerks"
5550 "Postal Service Mail Carriers"
5560 "Postal Service Mail Sorters, Processors, and Processing Machine Operators"
5600 "Production, Planning, and Expediting Clerks"
5610 "Shipping, Receiving, and Inventory Clerks"
5630 "Weighers, Measurers, Checkers, and Samplers, Recordkeeping"
5710 "Executive Secretaries and Executive Administrative Assistants"
5720 "Legal Secretaries and Administrative Assistants"
5730 "Medical Secretaries and Administrative Assistants"
5740 "Secretaries and Administrative Assistants, Except Legal, Medical, and Executive"
5810 "Data Entry Keyers"
5820 "Word Processors and Typists"
5830 "Desktop Publishers"
5840 "Insurance Claims and Policy Processing Clerks"
5850 "Mail Clerks and Mail Machine Operators, Except Postal Service"
5860 "Office Clerks, General"
5900 "Office Machine Operators, Except Computer"
5910 "Proofreaders and Copy Markers"
5920 "Statistical Assistants"
5940 "Office and Administrative Support Workers, All Other"
6005 "First-Line Supervisors of Farming, Fishing, and Forestry Workers"
6010 "Agricultural Inspectors"
6020 "Animal Breeders"
6040 "Graders and Sorters, Agricultural Products"
6050 "Miscellaneous Agricultural Workers"
6115 "Fishing and Hunting Workers"
6120 "Forest and Conservation Workers"
6130 "Logging Workers"
6200 "First-Line Supervisors of Construction Trades and Extraction Workers"
6210 "Boilermakers"
6220 "Brickmasons, Blockmasons, and Stonemasons"
6230 "Carpenters"
6240 "Carpet, Floor, and Tile Installers and Finishers"
6250 "Cement Masons, Concrete Finishers, and Terrazzo Workers"
6260 "Construction Laborers"
6305 "Construction Equipment Operators"
6330 "Drywall Installers, Ceiling Tile Installers, and Tapers"
6355 "Electricians"
6360 "Glaziers"
6400 "Insulation Workers"
6410 "Painters and Paperhangers"
6441 "Pipelayers"
6442 "Plumbers, Pipefitters, and Steamfitters"
6460 "Plasterers and Stucco Masons"
6500 "Reinforcing Iron and Rebar Workers"
6515 "Roofers"
6520 "Sheet Metal Workers"
6530 "Structural Iron and Steel Workers"
6540 "Solar Photovoltaic Installers"
6600 "Helpers, Construction Trades"
6660 "Construction and Building Inspectors"
6700 "Elevator and Escalator Installers and Repairers"
6710 "Fence Erectors"
6720 "Hazardous Materials Removal Workers"
6730 "Highway Maintenance Workers"
6740 "Rail-Track Laying and Maintenance Equipment Operators"
6750 "Septic Tank Servicers and Sewer Pipe Cleaners"
6765 "Miscellaneous Construction and Related Workers"
6800 "Derrick, Rotary Drill, and Service Unit Operators, Oil and Gas  "
6821 "Excavating and Loading Machine and Dragline Operators, Surface Mining"
6825 "Earth Drillers, Except Oil and Gas"
6835 "Explosives Workers, Ordnance Handling Experts, and Blasters"
6850 "Underground Mining Machine Operators"
6920 "Roustabouts, Oil and Gas"
6950 "Other Extraction Workers"
7000 "First-Line Supervisors of Mechanics, Installers, and Repairers"
7010 "Computer, Automated Teller, and Office Machine Repairers"
7020 "Radio and Telecommunications Equipment Installers and Repairers"
7030 "Avionics Technicians"
7040 "Electric Motor, Power Tool, and Related Repairers"
7050 "Electrical and Electronics Installers and Repairers, Transportation Equipment"
7100 "Electrical and Electronics Repairers, Industrial and Utility "
7110 "Electronic Equipment Installers and Repairers, Motor Vehicles"
7120 "Audiovisual Equipment Installers and Repairers "
7130 "Security and Fire Alarm Systems Installers"
7140 "Aircraft Mechanics and Service Technicians"
7150 "Automotive Body and Related Repairers"
7160 "Automotive Glass Installers and Repairers"
7200 "Automotive Service Technicians and Mechanics"
7210 "Bus and Truck Mechanics and Diesel Engine Specialists"
7220 "Heavy Vehicle and Mobile Equipment Service Technicians and Mechanics"
7240 "Small Engine Mechanics"
7260 "Miscellaneous Vehicle and Mobile Equipment Mechanics, Installers, and Repairers"
7300 "Control and Valve Installers and Repairers"
7315 "Heating, Air Conditioning, and Refrigeration Mechanics and Installers"
7320 "Home Appliance Repairers"
7330 "Industrial and Refractory Machinery Mechanics"
7340 "Maintenance and Repair Workers, General"
7350 "Maintenance Workers, Machinery"
7360 "Millwrights"
7410 "Electrical Power-Line Installers and Repairers"
7420 "Telecommunications Line Installers and Repairers"
7430 "Precision Instrument and Equipment Repairers"
7440 "Wind Turbine Service Technicians"
7510 "Coin, Vending, and Amusement Machine Servicers and Repairers"
7520 "Commercial Divers"
7540 "Locksmiths and Safe Repairers"
7550 "Manufactured Building and Mobile Home Installers"
7560 "Riggers"
7610 "Helpers--Installation, Maintenance, and Repair Workers"
7640 "Other Installation, Maintenance, and Repair Workers"
7700 "First-Line Supervisors of Production and Operating Workers"
7710 "Aircraft Structure, Surfaces, Rigging, and Systems Assemblers"
7720 "Electrical, Electronics, and Electromechanical Assemblers"
7730 "Engine and Other Machine Assemblers"
7740 "Structural Metal Fabricators and Fitters"
7750 "Other Assemblers and Fabricators"
7800 "Bakers"
7810 "Butchers and Other Meat, Poultry, and Fish Processing Workers"
7830 "Food and Tobacco Roasting, Baking, and Drying Machine Operators and Tenders"
7840 "Food Batchmakers"
7850 "Food Cooking Machine Operators and Tenders"
7855 "Food Processing Workers, All Other"
7905 "Computer Numerically Controlled Tool Operators and Programmers"
7925 "Forming Machine Setters, Operators, and Tenders, Metal and Plastic"
7950 "Cutting, Punching, and Press Machine Setters, Operators, and Tenders, Metal and Plastic"
8000 "Grinding, Lapping, Polishing, and Buffing Machine Tool Setters, Operators, and Tenders, Metal and Plastic"
8025 "Other Machine Tool Setters, Operators, and Tenders, Metal and Plastic"
8030 "Machinists"
8040 "Metal Furnace Operators, Tenders, Pourers, and Casters"
8060 "Model Makers and Patternmakers, Metal and Plastic"
8100 "Molders and Molding Machine Setters, Operators, and Tenders, Metal and Plastic"
8130 "Tool and Die Makers"
8140 "Welding, Soldering, and Brazing Workers"
8225 "Other Metal Workers and Plastic Workers"
8250 "Prepress Technicians and Workers"
8255 "Printing Press Operators"
8256 "Print Binding and Finishing Workers"
8300 "Laundry and Dry-Cleaning Workers"
8310 "Pressers, Textile, Garment, and Related Materials"
8320 "Sewing Machine Operators"
8335 "Shoe and Leather Workers"
8350 "Tailors, Dressmakers, and Sewers"
8365 "Textile Machine Setters, Operators, and Tenders"
8450 "Upholsterers"
8465 "Other Textile, Apparel, and Furnishings Workers"
8500 "Cabinetmakers and Bench Carpenters"
8510 "Furniture Finishers"
8530 "Sawing Machine Setters, Operators, and Tenders, Wood"
8540 "Woodworking Machine Setters, Operators, and Tenders, Except Sawing"
8555 "Other Woodworkers"
8600 "Power Plant Operators, Distributors, and Dispatchers"
8610 "Stationary Engineers and Boiler Operators"
8620 "Water and Wastewater Treatment Plant and System Operators"
8630 "Miscellaneous Plant and System Operators"
8640 "Chemical Processing Machine Setters, Operators, and Tenders"
8650 "Crushing, Grinding, Polishing, Mixing, and Blending Workers"
8710 "Cutting Workers"
8720 "Extruding, Forming, Pressing, and Compacting Machine Setters, Operators, and Tenders"
8730 "Furnace, Kiln, Oven, Drier, and Kettle Operators and Tenders"
8740 "Inspectors, Testers, Sorters, Samplers, and Weighers"
8750 "Jewelers and Precious Stone and Metal Workers"
8760 "Dental and Ophthalmic Laboratory Technicians and Medical Appliance Technicians"
8800 "Packaging and Filling Machine Operators and Tenders"
8810 "Painting Workers"
8830 "Photographic Process Workers and Processing Machine Operators"
8850 "Adhesive Bonding Machine Operators and Tenders"
8910 "Etchers and Engravers"
8920 "Molders, Shapers, and Casters, Except Metal and Plastic"
8930 "Paper Goods Machine Setters, Operators, and Tenders"
8940 "Tire Builders"
8950 "Helpers--Production Workers"
8865 "Other Production Equipment Operators and Tenders"
8990 "Other Production Workers"
9005 "Supervisors of Transportation and Material Moving Workers"
9030 "Aircraft Pilots and Flight Engineers"
9040 "Air Traffic Controllers and Airfield Operations Specialists"
9050 "Flight Attendants"
9110 "Ambulance Drivers and Attendants, Except Emergency Medical Technicians"
9121 "Bus Drivers, School"
9122 "Bus Drivers, Transit and Intercity"
9130 "Driver/Sales Workers and Truck Drivers"
9141 "Shuttle Drivers and Chauffeurs"
9142 "Taxi Drivers"
9150 "Motor Vehicle Operators, All Other"
9210 "Locomotive Engineers and Operators"
9240 "Railroad Conductors and Yardmasters"
9265 "Other Rail Transportation Workers"
9300 "Sailors and Marine Oilers"
9310 "Ship and Boat Captains and Operators"
9330 "Ship Engineers "
9350 "Parking Attendants"
9365 "Transportation Service Attendants"
9410 "Transportation Inspectors"
9415 "Passenger Attendants"
9430 "Other Transportation Workers"
9510 "Crane and Tower Operators"
9570 "Conveyor, Dredge, and Hoist and Winch Operators"
9600 "Industrial Truck and Tractor Operators"
9610 "Cleaners of Vehicles and Equipment"
9620 "Laborers and Freight, Stock, and Material Movers, Hand"
9630 "Machine Feeders and Offbearers"
9640 "Packers and Packagers, Hand"
9645 "Stockers and Order Fillers"
9650 "Pumping Station Operators"
9720 "Refuse and Recyclable Material Collectors"
9760 "Other Material Moving Workers"
9840 "Armed forces"
;
#delimit cr ;
lab val occ18 occ18
label var occ18 "2018 Census Occupation Classification"
notes occ18: Occupation classification for 2020m1-present
notes occ18: 2020m1-present CPS: peio1ocd
