********************************************************************************
* Occupation: 2018 classification
********************************************************************************
/* 2020m1-present: 2018 census occupation codes */
gen occ18 = .

if $monthlycps == 1 {
	if tm(2020m1) <= $date {
		replace occ18 = occcode
	}
}

#delimit ;
lab def occ18
0000 "N/A (not applicable)"
0010 "Chief executives"
0020 "General and operations managers"
0030 "Legislators"
0040 "Advertising and promotions managers"
0052 "Sales Managers"
0051 "Marketing Managers"
0060 "Public relations managers"
0101 "Administrative Services Managers"
0102 "Facilities Managers"
0110 "Computer and information systems managers"
0120 "Financial managers"
0135 "Compensation and Benefits Managers"
0136 "Human Resources Managers"
0137 "Training and Development Managers"
0140 "Industrial production managers"
0150 "Purchasing managers"
0160 "Transportation, storage, and distribution managers"
0205 "Farmers, Ranchers, and Other Agricultural Managers"
0220 "Construction managers"
0230 "Education administrators"
0300 "Engineering managers"
0310 "Food service managers"
0325 "Funeral service managers"
0335 "Entertainment and Recreation Managers"
0340 "Lodging managers"
0350 "Medical and health services managers"
0360 "Natural sciences managers"
0400 "Postmasters and mail superintendents"
0410 "Property, real estate, and community association managers"
0420 "Social and community service managers"
0425 "Emergency Management Directors"
0426 "Personal Service Managers, All Other"
0440 "Managers, All Other"
0500 "Agents and business managers of artists, performers, and athletes"
0510 "Purchasing agents and buyers, farm products"
0520 "Wholesale and retail buyers, except farm products"
0530 "Purchasing agents, except wholesale, retail, and farm products"
0540 "Claims adjusters, appraisers, examiners, and investigators"
0550 "Not used"
0565 "Compliance officers"
0600 "Cost estimators"
0610 "Not used"
0630 "Human resource workers"
0640 "Compensation, benefits, and job analysis specialists"
0650 "Training and development specialists"
0700 "Logisticians"
0705 "Project Management Specialists"
0710 "Management analysts"
0725 "Meeting, convention, and event planners"
0726 "Fundraisers"
0735 "Market research analysts and marketing specialists"
0750 "Business Operations Specialists, All Other"
0800 "Accountants and auditors"
0810 "Appraisers and assessors of real estate"
0820 "Budget analysts"
0830 "Credit analysts"
0845 "Financial and Investment Analysts"
0850 "Personal financial advisors"
0860 "Insurance underwriters"
0900 "Financial examiners"
0910 "Loan counselors and officers"
0920 "Not used"
0930 "Tax examiners, collectors, and revenue agents"
0940 "Tax preparers"
0960 "Other Financial Specialists"
1000 "Computer scientists and systems analysts"
1005 "Computer and information research scientists"
1006 "Computer systems analysts"
1007 "Information security analysts"
1010 "Computer programmers"
1020 "Software developers, applications and systems software"
1031 "Web Developers"
1032 "Web and Digital Interface Designers"
1050 "Computer support specialists"
1065 "Database Administrators and Architects"
1105 "Network and computer systems administrators"
1106 "Computer network architects"
1065 "Database Administrators and Architects"
1022 "Software Quality Assurance Analysts and Testers"
1032 "Web and Digital Interface Designers"
1108 "Computer Occupations, All Other"
1200 "Actuaries"
1210 "Mathematicians"
1220 "Operations research analysts"
1230 "Statisticians"
1240 "Miscellaneous mathematical science occupations"
1305 "Architects, Except Landscape and Naval"
1306 "Landscape Architects"
1310 "Surveyors, cartographers, and photogrammetrists"
1320 "Aerospace engineers"
1330 "Agricultural engineers"
1340 "Biomedical engineers"
1350 "Chemical engineers"
1360 "Civil engineers"
1400 "Computer hardware engineers"
1410 "Electrical and electronics engineers"
1420 "Environmental engineers"
1430 "Industrial engineers, including health and safety"
1440 "Marine engineers and naval architects"
1450 "Materials engineers"
1460 "Mechanical engineers"
1500 "Mining and geological engineers, including mining safety engineers"
1510 "Nuclear engineers"
1520 "Petroleum engineers"
1530 "Engineers, all other"
1541 "Architectural and Civil Drafters"
1545 "Other Drafters"
1551 "Electrical and Electronic Engineering Technologists and Technicians"
1555 "Other Engineering Technologists and Technicians, Except Drafters"
1560 "Surveying and mapping technicians"
1600 "Agricultural and food scientists"
1610 "Biological scientists"
1640 "Conservation scientists and foresters"
1650 "Medical scientists"
1660 "Life scientists, all other"
1700 "Astronomers and physicists"
1710 "Atmospheric and space scientists"
1720 "Chemists and materials scientists"
1730 "Not used"
1745 "Environmental Scientists and Specialists, Including Health"
1750 "Geoscientists and Hydrologists, Except Geographers"
1760 "Physical scientists, all other"
1800 "Economists"
1815 "Survey researchers"
1821 "Clinical and Counseling Psychologists"
1822 "School Psychologists"
1825 "Other Psychologists"
1830 "Sociologists"
1840 "Urban and regional planners"
1850 "Not used"
1860 "Miscellaneous social scientists and related workers"
1900 "Agricultural and food science technicians"
1910 "Biological technicians"
1920 "Chemical technicians"
1935 "Environmental Science and Geoscience Technicians"
1940 "Nuclear technicians"
1950 "Social science research assistants"
1970 "Other Life, Physical, and Social Science Technicians"
1980 "Occupational Health and Safety Specialists and Technicians"
2001 "Substance Abuse and Behavioral Disorder Counselors"
2002 "Educational, Guidance, and Career Counselors and Advisors"
2003 "Marriage and Family Therapists"
2004 "Mental Health Counselors"
2005 "Rehabilitation Counselors"
2006 "Counselors, All Other"
2011 "Child, Family, and School Social Workers"
2012 "Healthcare Social Workers"
2013 "Mental Health and Substance Abuse Social Workers"
2014 "Social Workers, All Other"
2015 "Probation officers and correctional treatment specialists"
2016 "Social and human service assistants"
2025 "Miscellaneous community and social service specialists, including health educators and community health workers"
2030 "Not used"
2040 "Clergy"
2050 "Directors, religious activities and education"
2060 "Religious workers, all other"
2100 "Lawyers, Judges, magistrates, and other judicial workers"
2105 "Judicial law clerks"
2110 "Judges, magistrates, and other judicial workers"
2145 "Paralegals and legal assistants"
2170 "Title Examiners, Abstractors, and Searchers"
2180 "Legal Support Workers, All Other"
2205 "Postsecondary Teachers"
2300 "Preschool and kindergarten teachers"
2310 "Elementary and middle school teachers"
2320 "Secondary school teachers"
2330 "Special education teachers"
2350 "Tutors"
2360 "Other Teachers and Instructors"
2400 "Archivists, curators, and museum technicians"
2435 "Librarians and Media Collections Specialists"
2440 "Library technicians"
2545 "Teaching Assistants"
2555 "Other Educational Instruction and Library Workers"
2600 "Artists and related workers"
2631 "Commercial and Industrial Designers"
2632 "Fashion Designers"
2633 "Floral Designers"
2634 "Graphic Designers"
2635 "Interior Designers"
2636 "Merchandise Displayers and Window Trimmers"
2640 "Other Designers"
2700 "Actors"
2710 "Producers and directors"
2721 "Athletes and Sports Competitors"
2722 "Coaches and Scouts"
2723 "Umpires, Referees, and Other Sports Officials"
2730 "Not used"
2740 "Dancers and choreographers"
2751 "Music Directors and Composers"
2752 "Musicians and Singers"
2755 "Disc Jockeys, Except Radio "
2770 "Entertainers and Performers, Sports and Related Workers, All Other"
2805 "Broadcast announcers and radio disc jockeys"
2810 "News analysts, reporters, and correspondents"
2825 "Public relations specialists"
2830 "Editors"
2840 "Technical writers"
2850 "Writers and authors"
2861 "Interpreters and Translators"
2865 "Media and Communication Workers, All Other"
2862 "Court Reporters and Simultaneous Captioners"
2905 "Broadcast, Sound, and Lighting Technicians"
2910 "Photographers"
2920 "Television, video, and motion picture camera operators and editors"
2970 "Media and Communication Equipment Workers, All Other"
3000 "Chiropractors"
3010 "Dentists"
3020 "Not used"
3030 "Dietitians and nutritionists"
3040 "Optometrists"
3050 "Pharmacists"
3065 "Emergency Medicine Physicians"
3070 "Radiologists"
3090 "Other Physicians"
3100 "Surgeons"
3110 "Physician assistants"
3120 "Podiatrists"
3140 "Audiologists"
3150 "Occupational therapists"
3160 "Physical therapists"
3200 "Radiation therapists"
3210 "Recreational therapists"
3220 "Respiratory therapists"
3230 "Speech-language pathologists"
3235 "Exercise Physiologists"
3245 "Therapists, all other"
3250 "Veterinarians"
3255 "Registered nurses"
3256 "Nurse anesthetists"
3257 "Nurse midwives"
3258 "Nurse practitioners"
3261 "Acupuncturists"
3270 "Healthcare Diagnosing or Treating Practitioners, All Other"
3300 "Clinical laboratory technologists and technicians"
3310 "Dental hygienists"
3321 "Cardiovascular Technologists and Technicians"
3322 "Diagnostic Medical Sonographers"
3323 "Radiologic Technologists and Technicians"
3324 "Magnetic Resonance Imaging Technologists"
3330 "Nuclear Medicine Technologists and Medical Dosimetrists"
3401 "Emergency Medical Technicians"
3402 "Paramedics"
3421 "Pharmacy Technicians"
3422 "Psychiatric Technicians"
3423 "Surgical Technologists"
3424 "Veterinary Technologists and Technicians"
3430 "Dietetic Technicians and Ophthalmic Medical Technicians"
3500 "Licensed practical and licensed vocational nurses"
3515 "Medical Records Specialists"
3520 "Opticians, dispensing"
3535 "Miscellaneous health technologists and technicians"
3545 "Miscellaneous Health Technologists and Technicians"
3550 "Other Healthcare Practitioners and Technical Occupations"
3600 "Nursing, psychiatric, and home health aides"
3602 "Personal Care Aides"
3610 "Occupational therapist assistants and aides"
3620 "Physical therapist assistants and aides"
3630 "Massage therapists"
3640 "Dental assistants"
3645 "Medical assistants"
3646 "Medical transcriptionists"
3647 "Pharmacy aides"
3648 "Veterinary assistants and labratory animal caretakers"
3649 "Phlebotmists"
3655 "Miscellaneous healthcare support occupations, including medical equipment preparers"
3700 "First-line supervisors/managers of correctional officers"
3710 "First-line supervisors/managers of police and detectives"
3720 "First-line supervisors/managers of fire fighting and preventions workers"
3725 "First-Line Supervisors of Security Workers"
3735 "First-Line Supervisors of Protective Service Workers, All Other"
3740 "Fire fighters"
3750 "Fire inspectors"
3801 "Bailiffs"
3802 "Correctional Officers and Jailers"
3810 "Not used"
3820 "Detectives and criminal investigators"
3830 "Fish and game wardens"
3840 "Parking enforcement workers"
3870 "Police Officers"
3900 "Animal control workers"
3910 "Private detectives and investigators"
3930 "Security guards and gaming surveillance officers"
3940 "Crossing guards"
3945 "Transportation security screeners"
3946 "School Bus Monitors"
3960 "Other Protective Service Workers"
4000 "Chefs and head cooks"
4010 "First-line supervisors/managers of food preparation and serving workers"
4020 "Cooks"
4030 "Food preparation workers"
4040 "Bartenders"
4055 "Fast Food and Counter Workers"
4110 "Waiters and waitresses"
4120 "Food servers, nonrestaurant"
4130 "Dining room and cafeteria attendants, bartender helpers, and miscellaneous food preparation and serving related workers"
4140 "Dishwashers"
4150 "Hosts and hostesses, restaurant, lounge, and coffee shop"
4160 "Food preparation and serving related workers, all other"
4200 "First-line supervisors/managers of housekeeping and janitorial workers"
4210 "First-line supervisors/managers of landscaping, lawn service, and groundskeeping workers"
4220 "Janitors and building cleaners"
4230 "Maids and housekeeping cleaners"
4240 "Pest control workers"
4251 "Landscaping and Groundskeeping Workers"
4252 "Tree Trimmers and Pruners"
4255 "Other Grounds Maintenance Workers"
4310 "Not used"
4330 "Supervisors of Personal Care and Service Workers"
4340 "Animal trainers"
4350 "Nonfarm animal caretakers"
4400 "Gaming services workers"
4420 "Ushers, lobby attendants, and ticket takers"
4435 "Other Entertainment Attendants and Related Workers"
4461 "Embalmers, Crematory Operators and Funeral Attendants"
4465 "Morticians, undertakers, and funeral directors (2011 forward)"
4500 "Barbers"
4510 "Hairdressers, hairstylists, and cosmetologists"
4521 "Manicurists and Pedicurists"
4522 "Skincare Specialists"
4525 "Other Personal Appearance Workers"
4530 "Baggage porters, bellhops, and concierges"
4540 "Tour and travel guides"
4550 "Transportation attendants"
4600 "Child care workers"
4610 "Personal and home care aides"
4621 "Exercise Trainers and Group Fitness Instructors"
4622 "Recreation Workers"
4630 "Not used"
4640 "Residential advisors"
4461 "Embalmers, Crematory Operators and Funeral Attendants"
4655 "Personal Care and Service Workers, All Other"
4700 "First-line supervisors/managers of retail sales workers"
4710 "First-line supervisors/managers of non-retail sales workers"
4720 "Cashiers"
4730 "Not used"
4740 "Counter and rental clerks"
4750 "Parts salespersons"
4760 "Retail salespersons"
4800 "Advertising sales agents"
4810 "Insurance sales agents"
4820 "Securities, commodities, and financial services sales agents"
4830 "Travel agents"
4840 "Sales representatives, services, all other"
4850 "Sales representatives, wholesale and manufacturing"
4900 "Models, demonstrators, and product promoters"
4910 "Not used"
4920 "Real estate brokers and sales agents"
4930 "Sales engineers"
4940 "Telemarketers"
4950 "Door-to-door sales workers, news and street vendors, and related workers"
4965 "Sales and related workers, all other"
5000 "First-line supervisors/managers of office and administrative support workers"
5010 "Switchboard operators, including answering service"
5020 "Telephone operators"
5040 "Communications Equipment Operators, All Other"
5100 "Bill and account collectors"
5110 "Billing and posting clerks and machine operators"
5120 "Bookkeeping, accounting, and auditing clerks"
5130 "Gaming cage workers"
5140 "Payroll and timekeeping clerks"
5150 "Procurement clerks"
5160 "Tellers"
5165 "Financial clerks, all other"
5200 "Brokerage clerks"
5210 "Correspondence clerks"
5220 "Court, municipal, and license clerks"
5230 "Credit authorizers, checkers, and clerks"
5240 "Customer service representatives"
5250 "Eligibility interviewers, government programs"
5260 "File clerks"
5300 "Hotel, motel, and resort desk clerks"
5310 "Interviewers, except eligibility and loan"
5320 "Library assistants, clerical"
5330 "Loan interviewers and clerks"
5340 "New accounts clerks"
5350 "Order clerks"
5360 "Human resources assistants, except payroll and timekeeping"
5400 "Receptionists and information clerks"
5410 "Reservation and transportation ticket agents and travel clerks"
5420 "Information and record clerks, all other"
5500 "Cargo and freight agents"
5510 "Couriers and messengers"
5521 "Public Safety Telecommunicators"
5522 "Dispatchers, Except Police, Fire, and Ambulance"
5530 "Meter readers, utilities"
5540 "Postal service clerks"
5550 "Postal service mail carriers"
5560 "Postal service mail sorters, processors, and processing machine operators"
5600 "Production, planning and expediting clerks"
5610 "Shipping, receiving, and traffic clerks"
5630 "Weighers, measurers, checkers, and samplers, record keeping"
5710 "Executive Secretaries and Executive Administrative Assistants"
5720 "Legal Secretaries and Administrative Assistants"
5730 "Medical Secretaries and Administrative Assistants"
5740 "Secretaries and Administrative Assistants, Except Legal, Medical, and Executive"
5810 "Data entry keyers"
5820 "Word processors and typists"
5830 "Desktop publishers"
5840 "Insurance claims and policy processing clerks"
5850 "Mail clerks and mail machine operators, except postal service"
5860 "Office clerks, general"
5900 "Office machine operators, except computer"
5910 "Proofreaders and copy markers"
5920 "Statistical assistants"
5940 "Office and administrative support workers, all other"
6005 "First-line supervisors of farming, fishing, and forestry workers"
6010 "Agricultural inspectors"
6020 "Animal breeders"
6030 "Not used"
6040 "Graders and sorters, agricultural products"
6050 "Miscellaneous agricultural workers"
6115 "Fishing and Hunting Workers"
6120 "Forest and conservation workers"
6130 "Logging workers"
6200 "First-line supervisors/managers of construction trades and extraction workers"
6210 "Boilermakers"
6220 "Brickmasons, blockmasons, and stonemasons"
6230 "Carpenters"
6240 "Carpet, floor, and tile installers and finishers"
6250 "Cement masons, concrete finishers, and terrazzo workers"
6260 "Construction laborers"
6305 "Construction Equipment Operators"
6330 "Drywall installers, ceiling tile installers, and tapers"
6340 "Not used"
6355 "Electricians"
6360 "Glaziers"
6400 "Insulation workers"
6410 "Painters and Paperhangers"
6441 "Pipelayers"
6442 "Plumbers, Pipefitters, and Steamfitters"
6450 "Not used"
6460 "Plasterers and stucco masons"
6500 "Reinforcing iron and rebar workers"
6515 "Roofers"
6520 "Sheet metal workers"
6530 "Solar Photovoltaic Installers"
6540 "Structural iron and steel workers"
6600 "Helpers, construction trades"
6660 "Construction and building inspectors"
6700 "Elevator installers and repairers"
6710 "Fence erectors"
6720 "Hazardous materials removal workers"
6730 "Highway maintenance workers"
6740 "Rail-track laying and maintenance equipment operators"
6750 "Septic tank servicers and sewer pipe cleaners"
6765 "Miscellaneous construction and related workers"
6800 "Derrick, rotary drill, and service unit operators, oil, gas, and mining"
6810 "Not used"
6821 "Excavating and Loading Machine and Dragline Operators, Surface Mining"
6825 "Earth Drillers, Except Oil and Gas"
6835 "Explosives Workers, Ordnance Handling Experts, and Blasters"
6835 "Explosives workers, ordnance handling experts, and blasters"
6850 "Underground Mining Machine Operators"
6920 "Roustabouts, oil and gas"
6950 "Other Extraction Workers"
7000 "First-line supervisors/managers of mechanics, installers, and repairers"
7010 "Computer, automated teller, and office machine repairers"
7020 "Radio and telecommunications equipment installers and repairers"
7030 "Avionics technicians"
7040 "Electric motor, power tool, and related repairers"
7050 "Electrical and electronics installers and repairers, transportation equipment"
7100 "Electrical and electronics repairers, industrial and utility"
7110 "Electronic equipment installers and repairers, motor vehicles"
7120 "Electronic home entertainment equipment installers and repairers"
7130 "Security and fire alarm systems installers"
7140 "Aircraft mechanics and service technicians"
7150 "Automotive body and related repairers"
7160 "Automotive glass installers and repairers"
7200 "Automotive service technicians and mechanics"
7210 "Bus and truck mechanics and diesel engine specialists"
7220 "Heavy vehicle and mobile equipment service technicians and mechanics"
7230 "Not used"
7240 "Small engine mechanics"
7250 "Not used"
7260 "Miscellaneous vehicle and mobile equipment mechanics, installers, and repairers"
7300 "Control and valve installers and repairers"
7315 "Heating, air conditioning, and refrigeration mechanics and installers"
7320 "Home appliance repairers"
7330 "Industrial and refractory machinery mechanics"
7340 "Maintenance and repair workers, general"
7350 "Maintenance workers, machinery"
7360 "Millwrights"
7410 "Electrical power-line installers and repairers"
7420 "Telecommunications line installers and repairers"
7430 "Precision instrument and equipment repairers"
7440 "Wind turbine service technicians"
7510 "Coin, vending, and amusement machine servicers and repairers"
7520 "Commercial divers"
7530 "Not used"
7540 "Locksmiths and safe repairers"
7550 "Manufactured building and mobile home installers"
7560 "Riggers"
7610 "Helpers--installation, maintenance, and repair workers"
7640 "Other Installation, Maintenance, and Repair Workers"
7700 "First-line supervisors/managers of production and operating workers"
7710 "Aircraft structure, surfaces, rigging, and systems assemblers"
7720 "Electrical, electronics, and electromechanical assemblers"
7730 "Engine and other machine assemblers"
7740 "Structural metal fabricators and fitters"
7750 "Miscellaneous assemblers and fabricators"
7800 "Bakers"
7810 "Butchers and other meat, poultry, and fish processing workers"
7820 "Not used"
7830 "Food and tobacco roasting, baking, and drying machine operators and tenders"
7840 "Food batchmakers"
7850 "Food cooking machine operators and tenders"
7855 "Food processing workers, all other"
7905 "Computer Numerically Controlled Tool Operatiors and Programmers "
7910 "Not used"
7925 "Forming Machine Setters, Operators, and Tenders, Metal and Plastic"
7950 "Cutting, punching, and press machine setters, operators, and tenders, metal and plastic"
8000 "Grinding, lapping, polishing, and buffing machine tool setters, operators, and tenders, metal and plastic"
8025 "Other Machine Tool Setters, Operators, and Tenders, Metal and Plastic "
8030 "Machinists"
8040 "Metal furnace and kiln operators and tenders"
8050 "Not used"
8060 "Model makers and patternmakers, metal and plastic"
8100 "Molders and molding machine setters, operators, and tenders, metal and plastic"
8110 "Not used"
8130 "Tool and die makers"
8140 "Welding, soldering, and brazing workers"
8225 "Other Metal Workers and Plastic Workers"
8250 "Prepress technicians and workers"
8255 "Printing machine operators"
8256 "Print binding and finishing workers"
8300 "Laundry and dry-cleaning workers"
8310 "Pressers, textile, garment, and related materials"
8320 "Sewing machine operators"
8335 "Shoe and Leather Workers"
8350 "Tailors, dressmakers, and sewers"
8365 "Textile Machine Setters, Operators, and Tenders"
8450 "Upholsterers"
8465 "Other Textile, Apparel, and Furnishings Workers"
8500 "Cabinetmakers and bench carpenters"
8510 "Furniture finishers"
8530 "Sawing machine setters, operators, and tenders, wood"
8540 "Woodworking machine setters, operators, and tenders, except sawing"
8555 "Other Woodworkers"
8600 "Power plant operators, distributors, and dispatchers"
8610 "Stationary engineers and boiler operators"
8620 "Water and liquid waste treatment plant and system operators"
8630 "Miscellaneous plant and system operators"
8640 "Chemical processing machine setters, operators, and tenders"
8650 "Crushing, grinding, polishing, mixing, and blending workers"
8710 "Cutting workers"
8720 "Extruding, forming, pressing, and compacting machine setters, operators, and tenders"
8730 "Furnace, kiln, oven, drier, and kettle operators and tenders"
8740 "Inspectors, testers, sorters, samplers, and weighers"
8750 "Jewelers and precious stone and metal workers"
8760 "Medical, dental, and ophthalmic laboratory technicians"
8800 "Packaging and filling machine operators and tenders"
8810 "Painting workers"
8820 "Not used"
8830 "Photographic process workers and processing machine operators"
8850 "Cementing and gluing machine operators and tenders"
8865 "Other Production Equipment Operators and Tenders "
8910 "Etchers and engravers"
8920 "Molders, shapers, and casters, except metal and plastic"
8930 "Paper goods machine setters, operators, and tenders"
8940 "Tire builders"
8950 "Helpers--production workers"
8990 "Other Production Workers"
9005 "Supervisors of Transportation and Material Moving Workers"
9030 "Aircraft pilots and flight engineers"
9040 "Air traffic controllers and airfield operations specialists"
9050 "Flight attendants"
9110 "Ambulance drivers and attendants, except emergency medical technicians"
9121 "Bus Drivers, School"
9122 "Bus Drivers, Transit and Intercity"
9141 "Shuttle Drivers and Chauffeurs"
9130 "Driver/sales workers and truck drivers"
9141 "Shuttle Drivers and Chauffeurs"
9142 "Taxi Drivers"
9150 "Motor vehicle operators, all other"
9210 "Locomotive Engineers and Operators"
9265 "Other Rail Transportation Workers"
9240 "Railroad conductors and yardmasters"
9250 "Not used"
9265 "Other Rail Transportation Workers"
9300 "Sailors and marine oilers"
9310 "Ship and boat captains and operators"
9320 "Not used"
9330 "Ship engineers"
9340 "Bridge and lock tenders"
9350 "Parking lot attendants"
9360 "Service station attendants"
9365 "Transportation Service Attendants"
9410 "Transportation inspectors"
9415 "Transportation attendants, except flight attendants"
9430 "Other Transportation Workers"
9510 "Crane and tower operators"
9760 "Other Material Moving Workers"
9570 "Conveyor, Dredge, and Hoist and Winch Operators"
9600 "Industrial truck and tractor operators"
9610 "Cleaners of vehicles and equipment"
9620 "Laborers and freight, stock, and material movers, hand"
9630 "Machine feeders and offbearers"
9640 "Packers and packagers, hand"
9645 "Stockers and Order Fillers"
9650 "Pumping station operators"
9720 "Refuse and recyclable material collectors"
9740 "Tank car, truck, and ship loaders"
9750 "Material moving workers, all other"
9840 "Armed forces"
;
#delimit cr ;
lab val occ18 occ18
label var occ18 "2018 Census Occupation Classification"
notes occ18: Occupation classification for 2020m1-present
notes occ18: 2020m1-present CPS: peio1ocd
