********************************************************************************
* Occupation: 2000 classification
********************************************************************************
/* 2003-2010m12: 2000 census occupation codes */
gen occ00 = .

if $monthlycps == 1 | $marchcps == 1 {
	if tm(2003m1) <= $date & $date <= tm(2010m12) {
		replace occ00 = occcode
	}
}

#delimit ;
lab def occ00
0000 "N/A (not applicable)"
0010 "Chief executives"
0020 "General and operations managers"
0040 "Advertising and promotions managers"
0050 "Marketing and sales managers"
0060 "Public relations managers"
0100 "Administrative services managers"
0110 "Computer and information systems managers"
0120 "Financial managers"
0130 "Human Resources Managers"
0140 "Industrial production managers"
0150 "Purchasing managers"
0160 "Transportation, storage, and distribution managers"
0200 "Farm, ranch, and other agricultural managers"
0210 "Farmers and ranchers"
0220 "Construction managers"
0230 "Education administrators"
0300 "Engineering managers"
0310 "Food service managers"
0320 "Funeral directors"
0330 "Gaming managers"
0340 "Lodging managers"
0350 "Medical and health services managers"
0360 "Natural sciences managers"
0410 "Property, real estate, and community association managers"
0420 "Social and community service managers"
0430 "Managers, all other"
0500 "Agents and business managers of artists, performers, and athletes"
0510 "Purchasing agents and buyers, farm products"
0520 "Wholesale and retail buyers, except farm products"
0530 "Purchasing agents, except wholesale, retail, and farm products"
0540 "Claims adjusters, appraisers, examiners, and investigators"
0560 "Compliance officers, except agriculture, construction, health and safety, and transportation"
0600 "Cost estimators"
0620 "Human resources, training, and labor relations specialists"
0700 "Logisticians"
0710 "Management analysts"
0720 "Meeting and convention planners"
0730 "Other business operations specialists"
0800 "Accountants and auditors"
0810 "Appraisers and assessors of real estate"
0820 "Budget analysts"
0830 "Credit analysts"
0840 "Financial analysts"
0850 "Personal financial advisors"
0860 "Insurance underwriters"
0900 "Financial examiners"
0910 "Loan counselors and officers"
0930 "Tax examiners, collectors, and revenue agents"
0940 "Tax preparers"
0950 "Financial specialists, all other"
1000 "Computer scientists and systems analysts"
1010 "Computer programmers"
1020 "Computer software engineers"
1040 "Computer support specialists"
1060 "Database administrators"
1100 "Network and computer systems administrators"
1110 "Network systems and data communication analysts"
1200 "Actuaries"
1210 "Mathematicians"
1220 "Operations research analysts"
1230 "Statisticians"
1240 "Miscellaneous mathematical science occupations"
1300 "Architects, except naval"
1310 "Surveyors, cartographers, and photogrammetrists"
1320 "Aerospace engineers"
1330 "Agricultural engineers"
1340 "Biomedical engineers"
1350 "Chemical engineers"
1360 "Civil engineers"
1400 "Computer hardware engineers"
1410 "Electrical and electronics engineers"
1420 "Environmental engineers"
1430 "Industrial engineers, including health and safety"
1440 "Marine engineers and naval architects"
1450 "Materials engineers"
1460 "Mechanical engineers"
1500 "Mining and geological engineers, including mining safety engineers"
1510 "Nuclear engineers"
1520 "Petroleum engineers"
1530 "Engineers, all other"
1540 "Drafters"
1550 "Engineering technicians, except drafters"
1560 "Surveying and mapping technicians"
1600 "Agricultural and food scientists"
1610 "Biological scientists"
1640 "Conservation scientists and foresters"
1650 "Medical scientists"
1700 "Astronomers and physicists"
1710 "Atmospheric and space scientists"
1720 "Chemists and materials scientists"
1740 "Environmental scientists and geoscientists"
1760 "Physical scientists, all other"
1800 "Economists"
1810 "Market and survey researchers"
1820 "Psychologists"
1830 "Sociologists"
1840 "Urban and regional planners"
1860 "Miscellaneous social scientists and related workers"
1900 "Agricultural and food science technicians"
1910 "Biological technicians"
1920 "Chemical technicians"
1930 "Geological and petroleum technicians"
1940 "Nuclear technicians"
1960 "Other life, physical, and social science technicians"
2000 "Counselors"
2010 "Social workers"
2020 "Miscellaneous community and social service specialists"
2030 "Not used"
2040 "Clergy"
2050 "Directors, religious activities and education"
2060 "Religious workers, all other"
2100 "Lawyers, Judges, magistrates, and other judicial workers"
2140 "Paralegals and legal assistants"
2150 "Miscellaneous legal support workers"
2200 "Postsecondary teachers"
2300 "Preschool and kindergarten teachers"
2310 "Elementary and middle school teachers"
2320 "Secondary school teachers"
2330 "Special education teachers"
2340 "Other teachers and instructors"
2400 "Archivists, curators, and museum technicians"
2430 "Librarians"
2440 "Library technicians"
2540 "Teacher assistants"
2550 "Other education, training, and library workers"
2600 "Artists and related workers"
2630 "Designers"
2700 "Actors"
2710 "Producers and directors"
2720 "Athletes, coaches, umpires, and related workers"
2730 "Not used"
2740 "Dancers and choreographers"
2750 "Musicians, singers, and related workers"
2760 "Entertainers and performers, sports and related workers, all other"
2800 "Announcers"
2810 "News analysts, reporters, and correspondents"
2820 "Public relations specialists"
2830 "Editors"
2840 "Technical writers"
2850 "Writers and authors"
2860 "Miscellaneous media and communications workers"
2900 "Broadcast and sound engineering technicians and radio operators"
2910 "Photographers"
2920 "Television, video, and motion picture camera operators and editors"
2960 "Media and communications workers, all other"
3000 "Chiropractors"
3010 "Dentists"
3020 "Not used"
3030 "Dietitians and nutritionists"
3040 "Optometrists"
3050 "Pharmacists"
3060 "Physicians and surgeons"
3110 "Physician assistants"
3120 "Podiatrists"
3130 "Registered nurses"
3140 "Audiologists"
3150 "Occupational therapists"
3160 "Physical therapists"
3200 "Radiation therapists"
3210 "Recreational therapists"
3220 "Respiratory therapists"
3230 "Speech-language pathologists"
3240 "Therapists, all other"
3250 "Veterinarians"
3260 "Health diagnosing and treating practitioners, all other"
3300 "Clinical laboratory technologists and technicians"
3310 "Dental hygienists"
3320 "Diagnostic related technologists and technicians"
3400 "Emergency medical technicians and paramedics"
3410 "Health diagnosing and treating practitioner support technicians"
3500 "Licensed practical and licensed vocational nurses"
3510 "Medical records and health information technicians"
3520 "Opticians, dispensing"
3530 "Miscellaneous health technologists and technicians"
3540 "Other healthcare practitioners and technical occupations"
3600 "Nursing, psychiatric, and home health aides"
3610 "Occupational therapist assistants and aides"
3620 "Physical therapist assistants and aides"
3630 "Massage therapists"
3640 "Dental assistants"
3650 "Medical assistants and other healthcare support occupations"
3700 "First-line supervisors/managers of correctional officers"
3710 "First-line supervisors/managers of police and detectives"
3720 "First-line supervisors/managers of fire fighting and preventions workers"
3730 "Supervisors, protective service workers, all other"
3740 "Fire fighters"
3750 "Fire inspectors"
3800 "Bailiffs, correctional officers, and jailers"
3810 "Not used"
3820 "Detectives and criminal investigators"
3830 "Fish and game wardens"
3840 "Parking enforcement workers"
3850 "Police and sheriff's patrol officers"
3860 "Transit and railroad police"
3900 "Animal control workers"
3910 "Private detectives and investigators"
3920 "Security guards and gaming surveillance officers"
3940 "Crossing guards"
3950 "Lifeguards and other protective service workers"
4000 "Chefs and head cooks"
4010 "First-line supervisors/managers of food preparation and serving workers"
4020 "Cooks"
4030 "Food preparation workers"
4040 "Bartenders"
4050 "Combined food preparation and serving workers, including fast food"
4060 "Counter attendants, cafeteria, food concession, and coffee shop"
4110 "Waiters and waitresses"
4120 "Food servers, nonrestaurant"
4130 "Dining room and cafeteria attendants, bartender helpers, and miscellaneous food preparation and serving related workers"
4140 "Dishwashers"
4150 "Hosts and hostesses, restaurant, lounge, and coffee shop"
4160 "Food preparation and serving related workers, all other"
4200 "First-line supervisors/managers of housekeeping and janitorial workers"
4210 "First-line supervisors/managers of landscaping, lawn service, and groundskeeping workers"
4220 "Janitors and building cleaners"
4230 "Maids and housekeeping cleaners"
4240 "Pest control workers"
4250 "Grounds maintenance workers"
4300 "First-line supervisors/managers of gaming workers"
4310 "Not used"
4320 "First-line supervisors/managers of personal service workers"
4330 "Not used"
4340 "Animal trainers"
4350 "Nonfarm animal caretakers"
4400 "Gaming services workers"
4410 "Motion picture projectionists"
4420 "Ushers, lobby attendants, and ticket takers"
4430 "Miscellaneous entertainment attendants and related workers"
4460 "Funeral service workers"
4500 "Barbers"
4510 "Hairdressers, hairstylists, and cosmetologists"
4520 "Miscellaneous personal appearance workers"
4530 "Baggage porters, bellhops, and concierges"
4540 "Tour and travel guides"
4550 "Transportation attendants"
4600 "Child care workers"
4610 "Personal and home care aides"
4620 "Recreation and fitness workers"
4630 "Not used"
4640 "Residential advisors"
4650 "Personal care and service workers, all other"
4700 "First-line supervisors/managers of retail sales workers"
4710 "First-line supervisors/managers of non-retail sales workers"
4720 "Cashiers"
4730 "Not used"
4740 "Counter and rental clerks"
4750 "Parts salespersons"
4760 "Retail salespersons"
4800 "Advertising sales agents"
4810 "Insurance sales agents"
4820 "Securities, commodities, and financial services sales agents"
4830 "Travel agents"
4840 "Sales representatives, services, all other"
4850 "Sales representatives, wholesale and manufacturing"
4900 "Models, demonstrators, and product promoters"
4910 "Not used"
4920 "Real estate brokers and sales agents"
4930 "Sales engineers"
4940 "Telemarketers"
4950 "Door-to-door sales workers, news and street vendors, and related workers"
4960 "Sales and related workers, all other"
5000 "First-line supervisors/managers of office and administrative support workers"
5010 "Switchboard operators, including answering service"
5020 "Telephone operators"
5030 "Communications equipment operators, all other"
5100 "Bill and account collectors"
5110 "Billing and posting clerks and machine operators"
5120 "Bookkeeping, accounting, and auditing clerks"
5130 "Gaming cage workers"
5140 "Payroll and timekeeping clerks"
5150 "Procurement clerks"
5160 "Tellers"
5200 "Brokerage clerks"
5210 "Correspondence clerks"
5220 "Court, municipal, and license clerks"
5230 "Credit authorizers, checkers, and clerks"
5240 "Customer service representatives"
5250 "Eligibility interviewers, government programs"
5260 "File clerks"
5300 "Hotel, motel, and resort desk clerks"
5310 "Interviewers, except eligibility and loan"
5320 "Library assistants, clerical"
5330 "Loan interviewers and clerks"
5340 "New accounts clerks"
5350 "Order clerks"
5360 "Human resources assistants, except payroll and timekeeping"
5400 "Receptionists and information clerks"
5410 "Reservation and transportation ticket agents and travel clerks"
5420 "Information and record clerks, all other"
5500 "Cargo and freight agents"
5510 "Couriers and messengers"
5520 "Dispatchers"
5530 "Meter readers, utilities"
5540 "Postal service clerks"
5550 "Postal service mail carriers"
5560 "Postal service mail sorters, processors, and processing machine operators"
5600 "Production, planning and expediting clerks"
5610 "Shipping, receiving, and traffic clerks"
5620 "Stock clerks and order fillers"
5630 "Weighers, measurers, checkers, and samplers, record keeping"
5700 "Secretaries and administrative assistants"
5800 "Computer operators"
5810 "Data entry keyers"
5820 "Word processors and typists"
5830 "Desktop publishers"
5840 "Insurance claims and policy processing clerks"
5850 "Mail clerks and mail machine operators, except postal service"
5860 "Office clerks, general"
5900 "Office machine operators, except computer"
5910 "Proofreaders and copy markers"
5920 "Statistical assistants"
5930 "Office and administrative support workers, all other"
6000 "First-line supervisors/managers of farming, fishing, and forestry workers"
6010 "Agricultural inspectors"
6020 "Animal breeders"
6030 "Not used"
6040 "Graders and sorters, agricultural products"
6050 "Miscellaneous agricultural workers"
6100 "Fishers and related fishing workers"
6110 "Hunters and trappers"
6120 "Forest and conservation workers"
6130 "Logging workers"
6200 "First-line supervisors/managers of construction trades and extraction workers"
6210 "Boilermakers"
6220 "Brickmasons, blockmasons, and stonemasons"
6230 "Carpenters"
6240 "Carpet, floor, and tile installers and finishers"
6250 "Cement masons, concrete finishers, and terrazzo workers"
6260 "Construction laborers"
6300 "Paving, surfacing, and tamping equipment operators"
6310 "Pile-driver operators"
6320 "Operating engineers and other construction equipment operators"
6330 "Drywall installers, ceiling tile installers, and tapers"
6340 "Not used"
6350 "Electricians"
6360 "Glaziers"
6400 "Insulation workers"
6410 "Not used"
6420 "Painters, construction and maintenance"
6430 "Paperhangers"
6440 "Pipelayers, plumbers, pipefitters, and steamfitters"
6450 "Not used"
6460 "Plasterers and stucco masons"
6500 "Reinforcing iron and rebar workers"
6510 "Roofers"
6520 "Sheet metal workers"
6530 "Structural iron and steel workers"
6600 "Helpers, construction trades"
6660 "Construction and building inspectors"
6700 "Elevator installers and repairers"
6710 "Fence erectors"
6720 "Hazardous materials removal workers"
6730 "Highway maintenance workers"
6740 "Rail-track laying and maintenance equipment operators"
6750 "Septic tank servicers and sewer pipe cleaners"
6760 "Miscellaneous construction and related workers"
6800 "Derrick, rotary drill, and service unit operators, and roustabouts, oil, gas, and mining"
6810 "Not used"
6820 "Earth drillers, except oil and gas"
6830 "Explosives workers, ordnance handling experts, and blasters"
6840 "Mining machine operators"
6910 "Roof bolters, mining"
6920 "Roustabouts, oil and gas"
6930 "Helpers -- extraction workers"
6940 "Other extraction workers"
7000 "First-line supervisors/managers of mechanics, installers, and repairers"
7010 "Computer, automated teller, and office machine repairers"
7020 "Radio and telecommunications equipment installers and repairers"
7030 "Avionics technicians"
7040 "Electric motor, power tool, and related repairers"
7050 "Electrical and electronics installers and repairers, transportation equipment"
7100 "Electrical and electronics repairers, industrial, utility, and transportation equipment"
7110 "Electronic equipment installers and repairers, motor vehicles"
7120 "Electronic home entertainment equipment installers and repairers"
7130 "Security and fire alarm systems installers"
7140 "Aircraft mechanics and service technicians"
7150 "Automotive body and related repairers"
7160 "Automotive glass installers and repairers"
7200 "Automotive service technicians and mechanics"
7210 "Bus and truck mechanics and diesel engine specialists"
7220 "Heavy vehicle and mobile equipment service technicians and mechanics"
7230 "Not used"
7240 "Small engine mechanics"
7250 "Not used"
7260 "Miscellaneous vehicle and mobile equipment mechanics, installers, and repairers"
7300 "Control and valve installers and repairers"
7310 "Heating, air conditioning, and refrigeration mechanics and installers"
7320 "Home appliance repairers"
7330 "Industrial and refractory machinery mechanics"
7340 "Maintenance and repair workers, general"
7350 "Maintenance workers, machinery"
7360 "Millwrights"
7410 "Electrical power-line installers and repairers"
7420 "Telecommunications line installers and repairers"
7430 "Precision instrument and equipment repairers"
7510 "Coin, vending, and amusement machine servicers and repairers"
7520 "Commercial divers"
7530 "Not used"
7540 "Locksmiths and safe repairers"
7550 "Manufactured building and mobile home installers"
7560 "Riggers"
7600 "Signal and track switch repairers"
7610 "Helpers--installation, maintenance, and repair workers"
7620 "Other installation, maintenance, and repair workers"
7700 "First-line supervisors/managers of production and operating workers"
7710 "Aircraft structure, surfaces, rigging, and systems assemblers"
7720 "Electrical, electronics, and electromechanical assemblers"
7730 "Engine and other machine assemblers"
7740 "Structural metal fabricators and fitters"
7750 "Miscellaneous assemblers and fabricators"
7800 "Bakers"
7810 "Butchers and other meat, poultry, and fish processing workers"
7820 "Not used"
7830 "Food and tobacco roasting, baking, and drying machine operators and tenders"
7840 "Food batchmakers"
7850 "Food cooking machine operators and tenders"
7900 "Computer control programmers and operators"
7910 "Not used"
7920 "Extruding and drawing machine setters, operators, and tenders, metal and plastic"
7930 "Forging machine setters, operators, and tenders, metal and plastic"
7940 "Rolling machine setters, operators, and tenders, metal and plastic"
7950 "Cutting, punching, and press machine setters, operators, and tenders, metal and plastic"
7960 "Drilling and boring machine tool setters, operators, and tenders, metal and plastic"
8000 "Grinding, lapping, polishing, and buffing machine tool setters, operators, and tenders, metal and plastic"
8010 "Lathe and turning machine tool setters, operators, and tenders, metal and plastic"
8020 "Milling and planing machine setters, operators, and tenders, metal and plastic"
8030 "Machinists"
8040 "Metal furnace and kiln operators and tenders"
8050 "Not used"
8060 "Model makers and patternmakers, metal and plastic"
8100 "Molders and molding machine setters, operators, and tenders, metal and plastic"
8110 "Not used"
8120 "Multiple machine tool setters, operators, and tenders, metal and plastic"
8130 "Tool and die makers"
8140 "Welding, soldering, and brazing workers"
8150 "Heat treating equipment setters, operators, and tenders, metal and plastic"
8160 "Lay-out workers, metal and plastic"
8200 "Plating and coating machine setters, operators, and tenders, metal and plastic"
8210 "Tool grinders, filers, and sharpeners"
8220 "Metalworkers and plastic workers,all others"
8230 "Bookbinders and bindery workers"
8240 "Job printers"
8250 "Prepress technicians and workers"
8260 "Printing machine operators"
8300 "Laundry and dry-cleaning workers"
8310 "Pressers, textile, garment, and related materials"
8320 "Sewing machine operators"
8330 "Shoe and leather workers and repairers"
8340 "Shoe machine operators and tenders"
8350 "Tailors, dressmakers, and sewers"
8360 "Textile bleaching and dyeing machine operators and tenders"
8400 "Textile cutting machine setters, operators, and tenders"
8410 "Textile knitting and weaving machine setters, operators, and tenders"
8420 "Textile winding, twisting, and drawing out machine setters, operators, and tenders"
8430 "Extruding and forming machine setters, operators, and tenders, synthetic and glass fibers"
8440 "Fabric and apparel patternmakers"
8450 "Upholsterers"
8460 "Textile, apparel, and furnishings workers, all others"
8500 "Cabinetmakers and bench carpenters"
8510 "Furniture finishers"
8520 "Model makers and patternmakers, wood"
8530 "Sawing machine setters, operators, and tenders, wood"
8540 "Woodworking machine setters, operators, and tenders, except sawing"
8550 "Woodworkers, all others"
8600 "Power plant operators, distributors, and dispatchers"
8610 "Stationary engineers and boiler operators"
8620 "Water and liquid waste treatment plant and system operators"
8630 "Miscellaneous plant and system operators"
8640 "Chemical processing machine setters, operators, and tenders"
8650 "Crushing, grinding, polishing, mixing, and blending workers"
8710 "Cutting workers"
8720 "Extruding, forming, pressing, and compacting machine setters, operators, and tenders"
8730 "Furnace, kiln, oven, drier, and kettle operators and tenders"
8740 "Inspectors, testers, sorters, samplers, and weighers"
8750 "Jewelers and precious stone and metal workers"
8760 "Medical, dental, and ophthalmic laboratory technicians"
8800 "Packaging and filling machine operators and tenders"
8810 "Painting workers"
8820 "Not used"
8830 "Photographic process workers and processing machine operators"
8840 "Semiconductor processors"
8850 "Cementing and gluing machine operators and tenders"
8860 "Cleaning, washing, and metal pickling equipment operators and tenders"
8900 "Cooling and freezing equipment operators and tenders"
8910 "Etchers and engravers"
8920 "Molders, shapers, and casters, except metal and plastic"
8930 "Paper goods machine setters, operators, and tenders"
8940 "Tire builders"
8950 "Helpers--production workers"
8960 "Production workers, all other"
9000 "Supervisors, transportation and material moving workers"
9030 "Aircraft pilots and flight engineers"
9040 "Air traffic controllers and airfield operations specialists"
9110 "Ambulance drivers and attendants, except emergency medical technicians"
9120 "Bus drivers"
9130 "Driver/sales workers and truck drivers"
9140 "Taxi drivers and chauffeurs"
9150 "Motor vehicle operators, all other"
9200 "Locomotive engineers and operators"
9230 "Railroad brake, signal, and switch operators"
9240 "Railroad conductors and yardmasters"
9250 "Not used"
9260 "Subway, streetcar, and other rail transportation workers"
9300 "Sailors and marine oilers"
9310 "Ship and boat captains and operators"
9320 "Not used"
9330 "Ship engineers"
9340 "Bridge and lock tenders"
9350 "Parking lot attendants"
9360 "Service station attendants"
9410 "Transportation inspectors"
9420 "Other transportation workers"
9500 "Conveyor operators and tenders"
9510 "Crane and tower operators"
9520 "Dredge, excavating, and loading machine operators"
9560 "Hoist and winch operators"
9600 "Industrial truck and tractor operators"
9610 "Cleaners of vehicles and equipment"
9620 "Laborers and freight, stock, and material movers, hand"
9630 "Machine feeders and offbearers"
9640 "Packers and packagers, hand"
9650 "Pumping station operators"
9720 "Refuse and recyclable material collectors"
9730 "Shuttle car operators"
9740 "Tank car, truck, and ship loaders"
9750 "Material moving workers, all other"
9840 "Armed forces"
;
#delimit cr ;
lab val occ00 occ00
label var occ00 "2000 Census Occupation Classification"
notes occ00: Occupation classification for 2003-2010m12
notes occ00: 2003-2010m12 CPS: peio1ocd
