********************************************************************************
* Industry: 1980 classification
********************************************************************************
/* 1983-1991: 1980 census industry codes */
gen ind80 = .
if tm(1983m1) <= $date & $date <= tm(1991m12) {
	replace ind80 = indcode
}
#delimit ;
lab def ind80
10 "Agricultural production, crops"
11 "Agricultural production, livestock"
20 "Agricultural services, except horticultural"
21 "Horticultural services"
30 "Forestry"
31 "Fishing, hunting, and trapping"
40 "Metal mining"
41 "Coal mining"
42 "Crude petroleum and natural gas extraction"
50 "Nonmetallic mining and quarrying, except fuel"
60 "All construction"
100 "Meat products"
101 "Dairy products"
102 "Canned and preserved fruits and vegetables"
110 "Grain mill products"
111 "Bakery products"
112 "Sugar and confectionery products"
120 "Beverage industries"
121 "Miscellaneous food preparations and kindred productss"
122 "Food industries, n.s."
130 "Tobacco manufactures"
132 "Knitting mills"
140 "Dyeing and finishing textiles, except wool and knit goods"
141 "Floor coverings, except hard surface"
142 "Yarn, thread, and fabric mills"
150 "Miscellaneous textile mill products"
151 "Apparel and accessories, except knit"
152 "Miscellaneous fabricated textile products"
160 "Pulp, paper, and paperboard mills"
161 "Miscellaneous paper and pulp products"
162 "Paperboard containers and boxes"
171 "Newspaper publishing and printing"
172 "Printing, publishing, and allied industries, except newspapers"
180 "Plastics, synthetics, and resins"
181 "Drugs"
182 "Soaps and cosmetics"
190 "Paints, varnishes, and related products"
191 "Agricultural chemicals"
192 "Industrial and miscellaneous chemicals"
200 "Petroleum refining"
201 "Miscellaneous petroleum and coal products"
210 "Tires and inner tubes"
211 "Other rubber products, and plastics footwear and belting"
212 "Miscellaneous plastics products"
220 "Leather tanning and finishing"
221 "Footwear, except rubber and plastic"
222 "Leather products, except footwear"
230 "Logging"
231 "Sawmills, planing mills, and millwork"
232 "Wood buildings and mobile homes"
241 "Miscellaneous wood products"
242 "Furniture and fixtures"
250 "Glass and glass products"
251 "Cement, concrete, gypsum, and plaster products"
252 "Structural clay products"
261 "Pottery and related products"
262 "Miscellaneous nonmetallic mineral and stone productss"
270 "Blast furnaces, steelworks, rolling and finishing mills"
271 "Iron and steel foundries"
272 "Primary aluminum industries"
280 "Other primary metal industries"
281 "Cutlery, handtools, and other hardware"
282 "Fabricated structural metal products"
290 "Screw machine products"
291 "Metal forgings and stampings"
292 "Ordnance"
300 "Miscellaneous fabricated metal products"
301 "Metal industries, n.s."
310 "Engines and turbines"
311 "Farm machinery and equipment"
312 "Construction and material handling machines"
320 "Metalworking machinery"
321 "Office and accounting machines"
322 "Electronic computing equipment"
331 "Machinery, except electrical, n.e.c."
332 "Machinery, n.s."
340 "Household appliances"
341 "Radio, T.V., and communication equipment"
342 "Electrical machinery, equipment, and supplies, n.e.c."
350 "Electrical machinery, equipment, and supplies, n.s."
351 "Motor vehicles and motor vehicle equipment"
352 "Aircraft and parts"
360 "Ship and boat building and repairing"
361 "Railroad locomotives and equipment"
362 "Guided missiles, space vehicles, and parts"
370 "Cycles and miscellaneous transportation equipment"
371 "Scientific and controlling instruments"
372 "Optical and health services and supplies"
380 "Photographic equipment and supplies"
381 "Watches, clocks, and clockwork operated devices"
382 "Professional equipment, n.s."
390 "Toys, amusement, and sporting goods"
391 "Miscellaneous manufacturing industries"
392 "Manufacturing industries, n.s."
400 "Railroads"
401 "Bus service and urban transit"
402 "Taxicab service"
410 "Trucking service"
411 "Warehousing and storage"
412 "U.S. Postal Service"
420 "Water transportation"
421 "Air transportation"
422 "Pipelines, except natural gas"
432 "Services incidental to transportation"
440 "Radio and television broadcasting"
441 "Telephone"
442 "Telegraph and miscellaneous communication services"
460 "Electric light and power"
461 "Gas and steam supply systems"
462 "Electric and gas, and other combinations"
470 "Water supply and irrigation"
471 "Sanitary services"
472 "Utilities, n.s."
500 "Motor vehicles and equipment"
501 "Furniture and home furnishings"
502 "Lumber and construction materials"
510 "Sporting goods, toys, and hobby goods"
511 "Metals and minerals, except petroleum"
512 "Electrical goods"
521 "Hardware, plumbing and heating supplies"
522 "Electrical and hardware products, n.s."
530 "Machinery, equipment, and supplies"
531 "Scrap and waste materials"
532 "Miscellaneous wholesale, durable goods"
540 "Paper and paper products"
541 "Drugs, chemicals, and allied products"
542 "Apparel, fabrics, and notions"
550 "Groceries and related products"
551 "Farm products--raw materials"
552 "Petroleum products"
560 "Alcoholic beverages"
561 "Farm supplies"
562 "Miscellaneous wholesale, nondurable goods"
571 "Wholesale trade, n.s."
580 "Lumber and building material retailing"
581 "Hardware stores"
582 "Retail nurseries and garden stores"
590 "Mobile home dealers"
591 "Department stores"
592 "Variety stores"
600 "Miscellaneous general merchandise stores"
601 "Grocery stores"
602 "Dairy products stores"
610 "Retail bakeries"
611 "Food stores, n.e.c."
612 "Motor vehicle dealers"
620 "Auto and home supply stores"
621 "Gasoline service stations"
622 "Miscellaneous vehicle dealers"
630 "Apparel and accessory stores, except shoe"
631 "Shoe stores"
632 "Furniture and home furnishings stores"
640 "Household appliances, T.V., and radio stores"
641 "Eating and drinking places"
642 "Drug stores"
650 "Liquor stores"
651 "Sporting goods, bicycles, and hobby stores"
652 "Book and stationery stores"
660 "Jewelry stores"
661 "Sewing, needlework, and piece goods stores"
662 "Mail order houses"
670 "Vending machine operators"
671 "Direct selling establishments"
672 "Fuel and ice dealers"
681 "Retail florists"
682 "Miscellaneous retail stores"
691 "Retail trade, n.s."
700 "Banking"
701 "Savings and loan associations"
702 "Credit agencies, n.e.c."
710 "Security, commodity brokerage, and investment companies"
711 "Insurance"
712 "Real estate, including real estate-insurance-law offices"
721 "Advertising"
722 "Services to dwellings and other buildings"
730 "Commercial research, development, and testing labs"
731 "Personnel supply services"
732 "Business management and consulting services"
740 "Computer and data processing services"
741 "Detective and protective services"
742 "Business services, n.e.c."
750 "Automotive services, except repair"
751 "Automotive repair shops"
752 "Electrical repair shops"
760 "Miscellaneous repair services"
761 "Private households"
762 "Hotels and motels"
770 "Lodging places, except hotels and motels"
771 "Laundry, cleaning, and garment services"
772 "Beauty shops"
780 "Barber shops"
781 "Funeral service and crematories"
782 "Shoe repair shops"
790 "Dressmaking shops"
791 "Miscellaneous personal services"
800 "Theaters and motion pictures"
801 "Bowling alleys, billiard and pool parlors"
802 "Miscellaneous entertainment and recreation services"
812 "Offices of physicians"
820 "Offices of dentists"
821 "Offices of chiropractors"
822 "Offices of optometrists"
830 "Offices of health practitioners, n.e.c."
831 "Hospitals"
832 "Nursing and personal care facilities"
840 "Health services, n.e.c."
841 "Legal services"
842 "Elementary and secondary schools"
850 "Colleges and universities"
851 "Business, trade, and vocational schools"
852 "Libraries"
860 "Educational services, n.e.c."
861 "Job training and vocational rehabilitation services"
862 "Child day care services"
870 "Residential care facilities, without nursing"
871 "Social services, n.e.c."
872 "Museums, art galleries, and zoos"
880 "Religious organizations"
881 "Membership organizations"
882 "Engineering, architectural, and surveying services"
890 "Accounting, auditing, and bookkeeping services"
891 "Noncommercial educational and scientific research"
892 "Miscellaneous professional and related services"
900 "Executive and legislative offices"
901 "General government, n.e.c."
910 "Justice, public order, and safety"
921 "Public finance, taxation, and monetary policy"
922 "Administration of human resources programs"
930 "Administration of environmental quality and housing programs"
931 "Administration of economic programs"
932 "National security and international affairs"
991 "Unemployed, last job Armed Forces"
992 "Unemployed, has not worked in last 5 years"
;
#delimit cr;
lab val ind80 ind80
label var ind80 "1980 Census Industry Classification"
notes ind80: Industry classification for 1983-1991
notes ind80: 1983-1991 Unicon: ind
