* some webdoc options to deal with formatting
webdoc set stlog
webdoc set _stlog

/***
.. This page is generated by createdocs.do. Do not manually edit this page.

***/

* Title section
local label: variable label `1'

webdoc put ================================================================================
webdoc put `1': `label'
webdoc put ================================================================================
webdoc put

* Title image
if "`4'" == "titleimage" {
	webdoc put .. image:: images/`1'_titleimage.svg
	webdoc put
}

* Description
webdoc put Description
webdoc put ================================================================================
webdoc append ${variableshortdesc}`1'_shortdesc.rst
webdoc put

* Availability
webdoc put Availability
webdoc put ================================================================================
webdoc append ${variableavailability}`1'_availability.rst
webdoc put

* Value labels
if "`2'" == "displayvalues" {
	webdoc put Values
	webdoc put ================================================================================
	webdoc put .. csv-table::
	webdoc put    :file: levels/`1'.csv
	webdoc put
}

* Detailed comments
if "`3'" == "details" {
	webdoc put Detailed comments
	webdoc put ================================================================================
	webdoc append ${variablelongdesc}`1'_longdesc.rst
	webdoc put
}

* Code for variable generation
webdoc put Code
webdoc put ================================================================================
webdoc put .. toggle-header::
webdoc put    :header: Variable creation (**show/hide code**)
webdoc put
webdoc put    .. literalinclude:: code/generate_`1'.do
webdoc put

* Code for detailed analysis
if "`4'" == "titleimage" {
	webdoc put .. toggle-header::
	webdoc put    :header: Figure above (**show/hide code**)
	webdoc put
	webdoc put    .. literalinclude:: code/`1'_analysis.do
	webdoc put
}

* Variable notes
webdoc put Variable notes
webdoc put ================================================================================
webdoc stlog, cmdstrip raw
notes `1'
webdoc stlog close
