* some webdoc options to deal with formatting
webdoc set stlog
webdoc set _stlog

webdoc put ---
webdoc put notes: This page is generated by createdocs.do. Do not manually edit this page.
webdoc put ---
webdoc put 

webdoc put # Available variables
webdoc put 
webdoc put Variable | Description
webdoc put ---------|------------

* variable-group definitions
import delimited using ${codedocs}variables_groups.csv, clear varnames(1)
tempfile groups
save `groups'
local N = _N
forvalues i = 1 / `N' {
	use `groups', clear
	keep if _n == `i'
	local var: di varname
	local group`var': di group
}

load_epiextracts, begin(2018m1) end(2018m1) sample(basic) version(local)
keep if _n == 1
order _all, alphabetic
foreach var of varlist _all {
  local label: variable label `var'
  webdoc put [\``var'\`](`group`var''/`var'.md) | `label'
}
