# Project information
site_name: EPI Microdata Extracts
site_description: CPS and other microdata extracts used by EPI
site_url: https://microdata.epi.org
copyright: 'Copyright &copy; 2023 <a href= "https://epi.org">Economic Policy Institute</a>'

theme:
  name: 'material'
  language: en
  features:
    - navigation.tabs
    - content.tabs.link
  #palette:
  #  primary: 'blue grey'
  #  accent:  'indigo'
  font:
    text: Roboto
    code: Fira Code
  favicon: assets/images/favicon.png
  custom_dir: theme_customizations

markdown_extensions:
  - attr_list
  - codehilite
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.details
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets:
      base_path: docs
  - toc:
      permalink: true

plugins:
  - search
  - markdownextradata: {}
  - awesome-pages
  - exclude:
      glob: 
        - misc/*.md

dev_addr: '127.0.0.1:8282'

extra:
  version: 1.0.47
  latestdata: 2023m11
  year: 2023
